CREATE DEFINER=`root`@`localhost` PROCEDURE `insFacVenta`(
	in unnFV varchar(45),
	in cdbarFV varchar(250),
	in fecFV date,
    in ptovtaFV varchar(45),
    in nroFV varchar(45),
	in tipoFV varchar(45),
	in subtFV double,
	in descFV double,
	in bimpFV double,
	in iv1FV double,
	in imiv1 double,
	in iv2FV double,
	in imiv2 double,
	in iv3FV double,
	in imiv3 double,
	in totFV double,
	in obsFV varchar(255),
    in usFV varchar(250),
    in caeFV varchar(250),
    in vtcaeFV date,
	in impFV varchar(2),
    in feimpFV date,
    in reimpFV varchar(2),
    in fereimpFV date,
    in idccvFV int(11)
	)
BEGIN
	INSERT INTO VentaFacturas (
		CodUN,
		CodBarra,
        FechaFac,
        PtoVta,
		NroFactura,
		TipoFactura,
		SubTotal,
		Descuento,
		BaseImponible,
		Iva1,
		ImpIva1,
		Iva2,
		ImpIva2,
		Iva3,
		ImpIva3,
		Total,
		Observaciones,
        Usuario,
        CAE,
        VtoCAE,
        Impreso,
        FecImpresion,
        Reimpreso,
        FecReimpresion,
        CtaCteVenta_idCtaCteVenta
)
	VALUES (unnFV, cdbarFV, fecFV, ptovtaFV, nroFV, tipoFV, subtFV, descFV, bimpFV, iv1FV, imiv1, iv2FV, imiv2, iv3FV, imiv3, totFV, obsFV, usFV, caeFV, vtcaeFV, impFV, feimpFV, reimpFV, fereimpFV, idccvFV);
END