CREATE DEFINER=`root`@`localhost` PROCEDURE `insServTecnico`(
	in cdunST varchar(45),
	in nrordST varchar(45),
	in cdbarST varchar(250),
	in fecST date,
	in tpeqST varchar(45),
	in deteqST varchar(255),
	in acceqST varchar(250),
	in eqcdbarST varchar(250),
	in probST longtext,
	in diagST varchar(255),
	in feestST date,
	in feentST date,
	in presupST double,
	in garST int(11),
	in vtogarST date,
	in facST varchar(2),
	in tercST varchar(2),
    in preproST double,
    in feentproST date,
    in ferecproST date,
    in obsST varchar(255),
    in usST varchar(250),
    in estST varchar(45),
    in idprovST int(11),
    in idclST int(11)
)
BEGIN
	INSERT INTO ServicioTecnico (
		CodUN,
		NroOrden,
        CodBarra,
		Fecha,
		TipoEquipo,
		DetalleEquipo,
		AccesoriosEquipo,
		EquipoCodBarra,
		Problema,
		Diagnostico,
		FecEstEntrega,
		FecEntrega,
		Presupuesto,
		GarantiaMeses,
		VtoGarantia,
		Facturado,
		Tercerizado,
        PresupuestoProv,
        FecEntregaProv,
        FecRecepcionProv,
		Observaciones,
        Usuario,
        Estado,
        Proveedores_IdProveedores,
        Clientes_IdClientes
)
	VALUES (cdunST, nrordST, cdbarST, fecST, tpeqST, deteqST, acceqST, eqcdbarST, probST, diagST, feestST, feentST, presupST, garST, vtogarST, facST, tercST, preproST, feentproST, ferecproST, obsST, usST, estST, idprovST, idclST);
END